// <auto-generated />
using BasicRest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasicRest.Migrations
{
    [DbContext(typeof(BasicContext))]
    [Migration("20200702033105_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("BasicRest.Models.BasicFib", b =>
                {
                    b.Property<int>("BasicFibId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fib")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Input")
                        .HasColumnType("INTEGER");

                    b.HasKey("BasicFibId");

                    b.ToTable("BasicFib");
                });
#pragma warning restore 612, 618
        }
    }
}
